### ISSUE TITLE
could you please help?

### ISSUE THREAD

**Issue by maksimKorzh** [dkappe/a0lite#6]
Hi Dietrich, this is not an issue with a0lite, but a fan's question

I know your name from CCC, I'm the author of BBC chess engine you might've heard of...
I'm researching your code several days in the row but getting a bit confused by one detail - 
your search seems to be MCTS that instead of rollouts uses policies/value NN predictions just like Leela do
but I can't see the way how a0lite can be used to train it's own network (most likely I can't see it due to my dumbness...)
So could you please answer several questions?

If so, here they are:
1. Is a0lite capable of training it's own network? (I mean adjusting policies/value output from self play) If so - how that can be done?
2. Is BadGyal your own network? (I've tested it in Arena - it's awesome!)
3. Is BadGyal trained using supervised or reinforcement learning (from a0lite self play?)
4. BadGyal seems to be a Leela compatible network at least from it's outputs' format perspective, so is it?

The reasons why I ask all these questions:
After completing 95 video series on alpha-beta engine in C I got very interested and MCTS + NN engines.
I've now implemented "vanilla" MCTS for tictactoe and it plays well. I understand that it's way different with chess...
I feel totally stuck now while trying to create/use NN to "guide" my tictactoe using policies/value predictions...
I read alpha zero papers and feel like understand the concept in general but my skills/understanding are too poor to
come up with some reasonable code on my own so I came across a0lite.

For my needs a0lite would be perfect if only it used CPU instead of GPU and handcrafted NN (so I could understand how it works) instead of pytorch.

My ultimate goal is to create a youtube tutorial series on how to create MCTS + NN chess engine.
I would even love to cover a0lite in this like series but pytorch is too complicated and known for it's installation issues on windows (I'm linux user, but most of my subscribers work on windows) and also I would like to pick up the simplest NN architecture possible. I'm not aming for strength or speed - 1600 Elo didactic engine would be perfect for start.

I know you probably busy with your own stuff, but if you could kindly show me the path I would greatly appreciate that.

Thanks in advance!
Maksim Korzh aka Code Monkey King

**Comment by dkappe** [comment]
So a0lite doesn’t have any self-play capabilities. The reasons for these are many fold, but primarily the main net, doesn’t use self-play but rather lichess data annotated with shallow SF10 multipv search. I resuscitated the supervised learning in leela shortly after joining the project. Then became interested in adding Q and policy data to SL data. This made a huge difference (200 elo) vs something like CCRL data without policy. You can find more info here: https://github.com/dkappe/leela-chess-weights/wiki/Bad-Gyal

Self-play is expensive. I’m able to achieve a good 300-400 elo stronger net with my approach in the same time. Also, the results are different and more interesting than just duplicating leela nets. I’d recommend dshawul (of Scorpio fame) and his training repo for a more digestible framework than the leela stuff.

**Comment by maksimKorzh** [comment]
Very clear, thanks for your response.
