### ISSUE TITLE
Number of threads used

### ISSUE THREAD

**Issue by fsmosca** [dkappe/a0lite#7]
My pc has 4 cores/8 threads, when a0lite is run it will use 4 threads. Is there any way to allow the user to control how many threads it should use?

**Comment by OfekShochat** [comment]
A0lite's search uses only 1 thread. The neural network library (badgyal) does that

**Comment by fsmosca** [comment]
Can we control the number of threads used by the the neural network library?

**Comment by OfekShochat** [comment]
Pytorch utilizes those threads. So you can set a limit with this (from documentation): https://pytorch.org/docs/stable/generated/torch.set_num_threads.html
So you can set that in the code

**Comment by fsmosca** [comment]
Thanks it worked.

I revised the `mgnet.py`, `meangirl_net.py`, `bgnet.py` and `badgyal_net.py`.

And couple of modifications in `engine.py` to expose the threads, cuda and net name.

```
A0 Lite
uci
id name A0 Lite
id author Dietrich Kappe
option name Threads type spin default 1 min 1 max 128
option name UseCuda type check default false
option name NetName type combo default meangirl var badgyal var meangirl
uciok
```

**Comment by OfekShochat** [comment]
Cool, that is a cool pr idea, make a branch on your fork

**Comment by fsmosca** [comment]
Changes are now in the [branch](https://github.com/fsmosca/a0lite/tree/torch_threads_option)

I change Threads to TorchCPUThreads so as not to be confused with the normal engine Threads.

```python
A0 Lite
uci
id name A0 Lite
id author Dietrich Kappe
option name TorchCPUThreads type spin default 1 min 1 max 128
option name UseCuda type check default false
option name NetName type combo default meangirl var badgyal var meangirl
uciok
```

There are also [minor changes](https://github.com/fsmosca/a0lite/commit/ef583d8462b7095b6e12f1a6de359d0c98682d1e#commitcomment-46985751) in the badgyal package.
